//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Input/Interact.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Interact: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Interact()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Interact"",
    ""maps"": [
        {
            ""name"": ""InteractAction"",
            ""id"": ""6dbd287d-7306-4299-94ff-d82d4d375a2a"",
            ""actions"": [
                {
                    ""name"": ""action"",
                    ""type"": ""Button"",
                    ""id"": ""ec61ba1d-5e0f-4178-ad9f-55d10eea8260"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""03f2c71e-dfde-475b-ad76-4292a855bbc0"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // InteractAction
        m_InteractAction = asset.FindActionMap("InteractAction", throwIfNotFound: true);
        m_InteractAction_action = m_InteractAction.FindAction("action", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // InteractAction
    private readonly InputActionMap m_InteractAction;
    private List<IInteractActionActions> m_InteractActionActionsCallbackInterfaces = new List<IInteractActionActions>();
    private readonly InputAction m_InteractAction_action;
    public struct InteractActionActions
    {
        private @Interact m_Wrapper;
        public InteractActionActions(@Interact wrapper) { m_Wrapper = wrapper; }
        public InputAction @action => m_Wrapper.m_InteractAction_action;
        public InputActionMap Get() { return m_Wrapper.m_InteractAction; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InteractActionActions set) { return set.Get(); }
        public void AddCallbacks(IInteractActionActions instance)
        {
            if (instance == null || m_Wrapper.m_InteractActionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InteractActionActionsCallbackInterfaces.Add(instance);
            @action.started += instance.OnAction;
            @action.performed += instance.OnAction;
            @action.canceled += instance.OnAction;
        }

        private void UnregisterCallbacks(IInteractActionActions instance)
        {
            @action.started -= instance.OnAction;
            @action.performed -= instance.OnAction;
            @action.canceled -= instance.OnAction;
        }

        public void RemoveCallbacks(IInteractActionActions instance)
        {
            if (m_Wrapper.m_InteractActionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInteractActionActions instance)
        {
            foreach (var item in m_Wrapper.m_InteractActionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InteractActionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InteractActionActions @InteractAction => new InteractActionActions(this);
    public interface IInteractActionActions
    {
        void OnAction(InputAction.CallbackContext context);
    }
}
